### ISSUE TITLE
0.7.4: pep517 build fails

### ISSUE THREAD

**Issue by kloczek** [alan-turing-institute/CleverCSV#77]
Looks like something is wrong
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 99, in <module>
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 86, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 59, in __init__
    self.set_defaults._disable()
AttributeError: 'MinimalDistribution' object has no attribute 'set_defaults'

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```
Here is list of installed modules in build env
<details>

```console
Package         Version
--------------- --------------
appdirs         1.4.4
attrs           22.1.0
Brlapi          0.8.3
build           0.9.0
contourpy       1.0.6
cssselect       1.1.0
cycler          0.11.0
distro          1.8.0
dnspython       2.2.1
exceptiongroup  1.0.0
extras          1.0.0
fixtures        4.0.0
fonttools       4.38.0
gpg             1.18.0-unknown
iniconfig       1.1.1
kiwisolver      1.4.4
libcomps        0.1.19
louis           3.24.0
lxml            4.9.1
matplotlib      3.6.2
numpy           1.23.1
olefile         0.46
packaging       21.3
pbr             5.9.0
pep517          0.13.0
Pillow          9.3.0
pip             22.3.1
pluggy          1.0.0
ply             3.11
PyGObject       3.42.2
pyparsing       3.0.9
pytest          7.2.0
python-dateutil 2.8.2
rpm             4.17.0
scour           0.38.2
setuptools      65.6.3
six             1.16.0
testtools       2.5.0
tomli           2.0.1
wheel           0.38.4
```
</details>

**Comment by mweinelt** [comment]
Broken by setuptools 65.6.0, works with 65.5.1.

**Comment by mweinelt** [comment]
Bisected to 

```
9b8a6ef60b2b490bcf60b9dd7f0d43d46f49e489 is the first bad commit
commit 9b8a6ef60b2b490bcf60b9dd7f0d43d46f49e489
Merge: a0e8e53c e0787fad
Author: Jason R. Coombs <jaraco@jaraco.com>
Date:   Sun Nov 13 14:37:35 2022 -0500

    Merge https://github.com/pypa/distutils into distutils-e0787fa

 setuptools/_distutils/README                       |  11 --
 setuptools/_distutils/__init__.py                  |  12 +-
 setuptools/_distutils/_collections.py              | 138 +++++++++++++++++++++
 setuptools/_distutils/_log.py                      |   4 +
 setuptools/_distutils/_msvccompiler.py             |   8 +-
 setuptools/_distutils/archive_util.py              |   8 +-
 setuptools/_distutils/bcppcompiler.py              |  12 +-
 setuptools/_distutils/ccompiler.py                 |  14 +--
 setuptools/_distutils/cmd.py                       |  19 ++-
 setuptools/_distutils/command/bdist.py             |   8 +-
 setuptools/_distutils/command/bdist_dumb.py        |  12 +-
 setuptools/_distutils/command/bdist_rpm.py         |  12 +-
 setuptools/_distutils/command/build.py             |   8 +-
 setuptools/_distutils/command/build_clib.py        |  12 +-
 setuptools/_distutils/command/build_ext.py         |  34 ++---
 setuptools/_distutils/command/build_py.py          |  12 +-
 setuptools/_distutils/command/build_scripts.py     |   8 +-
 setuptools/_distutils/command/check.py             |   4 +-
 setuptools/_distutils/command/clean.py             |   8 +-
 setuptools/_distutils/command/config.py            |  18 +--
 setuptools/_distutils/command/install.py           |  20 +--
 setuptools/_distutils/command/install_data.py      |   4 +-
 setuptools/_distutils/command/install_egg_info.py  |   5 +-
 setuptools/_distutils/command/install_headers.py   |   2 +-
 setuptools/_distutils/command/install_lib.py       |   6 +-
 setuptools/_distutils/command/install_scripts.py   |   4 +-
 setuptools/_distutils/command/register.py          |  18 +--
 setuptools/_distutils/command/sdist.py             |  20 +--
 setuptools/_distutils/command/upload.py            |  20 +--
 setuptools/_distutils/config.py                    |   2 +-
 setuptools/_distutils/core.py                      |  12 +-
 setuptools/_distutils/cygwinccompiler.py           |  82 ++++++------
 setuptools/_distutils/dep_util.py                  |   2 +-
 setuptools/_distutils/dir_util.py                  |   6 +-
 setuptools/_distutils/dist.py                      |  17 +--
 setuptools/_distutils/fancy_getopt.py              |   2 +-
 setuptools/_distutils/file_util.py                 |   4 +-
 setuptools/_distutils/filelist.py                  |  22 ++--
 setuptools/_distutils/log.py                       |  78 +++---------
 setuptools/_distutils/msvc9compiler.py             |   8 +-
 setuptools/_distutils/msvccompiler.py              |   6 +-
 setuptools/_distutils/spawn.py                     |   6 +-
 setuptools/_distutils/sysconfig.py                 |   8 +-
 setuptools/_distutils/tests/support.py             |  28 +----
 setuptools/_distutils/tests/test_archive_util.py   |   2 +-
 setuptools/_distutils/tests/test_bdist_dumb.py     |   1 -
 setuptools/_distutils/tests/test_bdist_rpm.py      |   1 -
 setuptools/_distutils/tests/test_build.py          |   2 +-
 setuptools/_distutils/tests/test_build_clib.py     |   2 +-
 setuptools/_distutils/tests/test_build_ext.py      |   3 +-
 setuptools/_distutils/tests/test_build_py.py       |  22 ++--
 setuptools/_distutils/tests/test_build_scripts.py  |   2 +-
 setuptools/_distutils/tests/test_check.py          |   2 +-
 setuptools/_distutils/tests/test_clean.py          |   2 +-
 setuptools/_distutils/tests/test_cmd.py            |  21 +---
 setuptools/_distutils/tests/test_config.py         |   6 +-
 setuptools/_distutils/tests/test_config_cmd.py     |   4 +-
 setuptools/_distutils/tests/test_core.py           |  21 +---
 setuptools/_distutils/tests/test_dir_util.py       |  33 ++---
 setuptools/_distutils/tests/test_dist.py           |  45 +++----
 setuptools/_distutils/tests/test_file_util.py      |  20 +--
 setuptools/_distutils/tests/test_filelist.py       |  75 ++++++-----
 setuptools/_distutils/tests/test_install.py        |  18 +--
 setuptools/_distutils/tests/test_install_data.py   |   1 -
 .../_distutils/tests/test_install_headers.py       |   1 -
 setuptools/_distutils/tests/test_install_lib.py    |   5 +-
 .../_distutils/tests/test_install_scripts.py       |   2 +-
 setuptools/_distutils/tests/test_log.py            |  53 ++------
 setuptools/_distutils/tests/test_register.py       |  11 +-
 setuptools/_distutils/tests/test_sdist.py          |  44 +++----
 setuptools/_distutils/tests/test_spawn.py          |   2 +-
 setuptools/_distutils/tests/test_upload.py         |  15 ++-
 setuptools/_distutils/unixccompiler.py             |  10 +-
 setuptools/_distutils/util.py                      |   8 +-
 setuptools/_distutils/versionpredicate.py          |  10 +-
 75 files changed, 557 insertions(+), 631 deletions(-)
 delete mode 100644 setuptools/_distutils/README
 create mode 100644 setuptools/_distutils/_log.py
```

**Comment by kloczek** [comment]
> Broken by setuptools 65.6.0, works with 65.5.1.

What I've pasted was with `setuptools` 65.6.3.

**Comment by mweinelt** [comment]
@kloczek Please test #81.

**Comment by kloczek** [comment]
It builds with that commit now however I would add below patch as well
```patch
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,3 +1,6 @@
+[build-system]
+requires = ["setuptools", "cython"]
+
 [tool.black]
 line-length=79
```
Thank you 👍
